get_filename_component(VS_INSTALL_DIR ${CMAKE_VS_DEVENV_COMMAND} DIRECTORY)
set(VS_INSTALL_DIR ${VS_INSTALL_DIR}/../..)
if (EXISTS ${VS_INSTALL_DIR}/VSSDK)
	set(VSSDKROOT ${VS_INSTALL_DIR}/VSSDK/VisualStudioIntegration)
elseif (DEFINED ENV{VSSDK140Install})
	set(VSSDKROOT $ENV{VSSDK140Install}/VisualStudioIntegration)
elseif (DEFINED ENV{VSSDK120Install})
	set(VSSDKROOT $ENV{VSSDK120Install}/VisualStudioIntegration)
else()
	set(VSSDKROOT $ENV{VSSDK100Install}/VisualStudioIntegration)
endif()
set(VSSDKINCLUDE ${VSSDKROOT}/Common/Inc)
set(VSSDKBIN ${VSSDKROOT}/Tools/Bin)

include_directories(${VSSDKINCLUDE})
include_directories(${CMAKE_CURRENT_LIST_DIR}/../../compat/vssdk)
